# Google Cloud Service Account credentials
[gcp_service_account]
type = "service_account"
project_id = "spcamapps"
private_key_id = "c14469c10eea7079d14a52bf4ca384ba9be1d0c8"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDrUEzo5BQALc3H
+wM9d7MM0n0icoaEOeDS/O5Nwe4aF0lSfp/OI5lXehXuliDxs3eXWd9hwm0+ZoBK
2rtqCYGwvntwKj5idO/nY8Y/XfM6M1FOUrPQ+4eTvm7mYiD65G3HEZLXnfZv0rgw
JQpAkPlIdfwWndniRPV4nVttoDhRpmbhOM1J3rnJo6SUyhwiaoCFdSbe21P+qBlk
HRTXTw59dMHmdfEXtViWk3C/mQYd5MtVu5b+7drZmY+2qCA7BhagaHWcJh7+lWgD
c8YmVu7vTS+hYd50lBtKREB+g0AR45iZcZYIWRXLeMuQx8WbB/JHr84XCiF7kwFz
va59SRRRAgMBAAECggEAI+jfW8Or6Qe/Dq9tI/0M0L5HGgcnz6zfdNiOwJoBgm90
S90Go8LF/KtPsSxYPwT4EUZF8xlkahs3+nRdGQZLXtQAFV1fo3nHPzn4KnplYEfY
NrTN5myZbiqnqjZmZF3mAh+El61DoCFO5LX6VbZp/FdY+YCW8VM8XJmINsy2W4CC
MJFW/NNgvnumxYEyF3V76+pxeVqqGVXk9lXUK7hGwRC0Up2eAPyywMtcwf7dayPo
NEGGtuq8iNugtguSjDSfYtkWU2+E5ci3KLnfaNOsWglCpIdlTDJw9xZdeJBLdyJb
SH4S/YGeCo8/fF+6ox+fIfwXjzy31FY6bV8ZVEX7qwKBgQD/qejbd/ebNpBdfWQx
UZDnVeCpQ2YcAcfakH8pb35A0N2HzKBaROWIvwDk4tgCx8ice+nSAC01tV/TVMqu
pvkzoQU42Ud8OAawfCkRy/JNYovmpYpFt6v/MqLlwiMJ2PG4eAW+EYMKjuAZToDg
hFVVwxxpH0a3sjVq2Bwk3DZT7wKBgQDrn4nOJFmXfWW17Ccd5RzDhHEeT3yWa2Dh
PgmcPKtA1b5GF+y0V7tcvJyP3QUDgcMAsxS6UGiC9EuUWTBbycP9A3IJWEH/yqrM
XJdGRbVl2iuaGyi9RWErwccp++AOK1CQs96kc9G+DHQxnjP+1rlhJ9p1iJErOeAy
567uuT3bvwKBgFT5DfHTv7IQwo6wHFrf9z9MJa1cP1XTqa8VE46cBeRZBygZdLpL
59Y5VXy9gHn8GMsZzC8F7ADL1ZuRtQOzb2QfgnLQlJfOrzp9KdFGbbQWqtTv9DMT
xtC87bNbgPXG6yAalB4GB/28WvNOSjtVAF/Ox2SRBpoLWwG17jS6FDx1AoGBAL8p
FjJqh01CbSxlRW8ZnHZ7kxKWRmv6/gR/wmhBSGc3gkF305CUxOt+Ej8df53SvxRo
Nd7asY/dBxx6J6OwVBOHohM2yYTvNhbK3+ghUgQqNsm2Ux0LlsRbWGwVbzfPqHNd
mrotRPM9Q1+mDGUqbAgIv1Iv1CcPs3dZRDFllGwdAoGALEAUeUYaaUTSbK8rISIP
GHDZL8EmP6aHdJgoxCmbvQvXqkXxChj44eVW4d7ttu34uLKp55iWQQvRcFtuDdpM
XI6L3rt+/ygpUt1m0NR5PP5rkapOkw+wyB8naP3IdZVvIkfTMWHWutAP3RUsqY8B
mhxWJhKGqx3YxtykpuQrc9Q=
-----END PRIVATE KEY-----'''
client_email = "spcamapps@spcamapps.iam.gserviceaccount.com"
client_id = "113226652637020297384"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/spcamapps%40spcamapps.iam.gserviceaccount.com" 